config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :slides
  resources :logins

  #root to: 'slides#index'
  root to: 'logins#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index

  end

  def new
  end
  def show
  end
    
  def create
    session[:nickname] = params[:user]
    redirect_to login_url("show")
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  def index
    @rooms = Room.all.order(:id)
  end

  def show
    @room = Room.find(params[:id])
    @user = session[:nickname] != "" ? session[:nickname] : "guest"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/layouts/application.html.slim
DOCTYPE
html
  head
    title
      | SlideShow
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track':'reload'
  body
    nav
      .navbar-header
        li = link_to 'TopPage', logins_path, class:'navbar-brand'
        li = link_to 'ChannelPage', slides_path, class:'navbar-brand'
    = yield

app/views/logins/index.html.slim
h1 ログイン

= form_tag logins_path,{method: 'post', class: 'form-horizontal', id: 'login-form'} do |f|
  .form-group
    = label_tag 'user', 'NickName if you want', class: 'col-sm-2 control-label'
    .col-sm-4
      = text_field_tag 'user', '', class: 'form-control'
  .form-group
    .col-sm-2
      = submit_tag 'Start', class: 'btn btn-default'

app/views/logins/show.html.slim
= react_component 'Start', prerender: true

app/views/slides/index.html.slim
#room
  h2 どの部屋に入りますか？
  - @rooms.each do |room|
    li
      = link_to "ROOM#{room.id}", slide_path(room)
  

app/views/slides/show.html.slim
h3 = "ROOM#{@room.id} #{@room.content}部屋"
= react_component 'Root', {user: @user, room: @room}